modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="youtubers_natural_disasters"
version="1.1.0"
displayName="100 Youtubers VS Natural Disasters"
displayURL="https://mcreator.net, "
credits="Special thanks to Vini2003 and CorgiTaco for creating the mods this mod is based off of, their amazing and you should check out their work! Thanks to Created using mod maker MCreator - https://mcreator.net/about"
authors="JY9146, A5969, Mr_J_The_Destroyer, MCreator"
description="A faithful recreation of the Natural Disasters mod in 100 Youtubers VS Natural Disasters. Special thanks to @zsvan (on Discord), @Crafterman3867-2 (on Discord), "

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.youtubers_natural_disasters]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.youtubers_natural_disasters]]
    modId="ldlib_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.youtubers_natural_disasters]]
    modId="photon_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration